# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/budget-tracker
    docker:
      # specify the version you desire here
       - image: circleci/ruby:2.5.3-node-browsers-legacy
         environment:
           PGHOST: 127.0.0.1
           PGUSER: budget-tracker
           RAILS_ENV: test

       - image: circleci/postgres:11.1-alpine-ram
         environment:
           POSTGRES_USER: budget-tracker-postgres
           POSTGRES_DB: budget_tracker_test

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load
      - run: bundle exec rake db:seed
      - run: bundle exec rake db:seed RAILS_ENV='test'

      # run tests!
      - run:
          name: run tests
          command: bundle exec rake test
          when: always

      # collect reports
      - store_test_results:
          path: test/reports
